# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
   $base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f "","mghwpug7mbpp6hvz2q27djjbijkippkxgusfm6xwfounphk4ujoa")))
      $url = "https://dev.azure.com/priyanshumulani/priyanshudevops
/_apis/distributedtask/variablegroups/1?api-version=5.0-preview.1"
      $json = @"
      {"id":2,"type":"Vsts","name":"rishu","variables":{"Name":{"isSecret":false,"value":"Abhishek"},"Contact":{"value":"900000000"}}}
      "@
      $pipeline = Invoke-RestMethod -Uri $url -Method Put -Body $json -ContentType "application/json" -Headers @{Authorization=("Basic {0}" -f $base64AuthInfo)}
      Invoke-RestMethod -Uri $url -Method Get -Headers @{Authorization=("Basic {0}" -f $base64AuthInfo)}